In [2]:
import gym
from gym import error, spaces
from gym.utils import seeding
import matplotlib.pyplot as plt
import numpy as np
import os

from gym_azul.envs.azul_env import AzulEnv
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

Num GPUs Available:  1


In [3]:
steps = 100
total_reward = 0
with AzulEnv() as env:
    print(env.observation_space)
    for i in range(steps):
        env.render()
        obs, reward, done, info = env.step(env.action_space.sample())
        total_reward += reward
        if done:
            break
total_reward

MultiDiscrete([21 21 21 21 21  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5
  5  5  5  5  5  5  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  3  4  5  6  5  5  5  5  5  8])

---------------
Factories:
[[0 0 0 0 0]
 [0 1 0 2 1]
 [0 0 2 1 1]
 [1 0 0 2 1]
 [1 1 0 0 2]
 [0 1 1 1 1]]

Wall:
0 [0 0 0 0 0]
0 [0 0 0 0 0]
0 [0 0 0 0 0]
0 [0 0 0 0 0]
0 [0 0 0 0 0]


---------------
Factories:
[[0 0 0 0 0]
 [0 1 0 2 1]
 [0 0 2 1 1]
 [1 0 0 2 1]
 [1 1 0 0 2]
 [0 1 1 1 1]]

Wall:
0 [0 0 0 0 0]
0 [0 0 0 0 0]
0 [0 0 0 0 0]
0 [0 0 0 0 0]
0 [0 0 0 0 0]


---------------
Factories:
[[0 0 0 0 0]
 [0 1 0 2 1]
 [0 0 2 1 1]
 [1 0 0 2 1]
 [1 1 0 0 2]
 [0 1 1 1 1]]

Wall:
0 [0 0 0 0 0]
0 [0 0 0 0 0]
0 [0 0 0 0 0]
0 [0 0 0 0 0]
0 [0 0 0 0 0]


---------------
Factories:
[[0 0 0 0 0]
 [0 1 0 2 1]
 [0 0 2 1 1]
 [1 0 0 2 1]
 [1 1 0 0 2]
 [0 1 1 1 1]]

Wall:
0 [0 0 0 0 0]
0 [0 0 0 0 0]
0 [0 0 0 0 0]
0 [0 0 0 0 0]
0 [0 0 0 0 0]


---------------
Factories:
[[0 0 0 0 0]

0 [0 0 0 0 0]


---------------
Factories:
[[3 2 4 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Wall:
0 [0 0 1 1 1]
1 [0 0 0 0 0]
1 [0 0 0 0 0]
1 [0 0 0 0 0]
0 [0 0 0 0 0]


---------------
Factories:
[[3 2 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Wall:
0 [0 0 1 1 1]
1 [0 0 0 0 0]
1 [0 0 0 0 0]
1 [0 0 0 0 0]
0 [0 0 0 0 0]


---------------
Factories:
[[3 2 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Wall:
0 [0 0 1 1 1]
1 [0 0 0 0 0]
1 [0 0 0 0 0]
1 [0 0 0 0 0]
0 [0 0 0 0 0]


---------------
Factories:
[[3 2 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Wall:
0 [0 0 1 1 1]
1 [0 0 0 0 0]
1 [0 0 0 0 0]
1 [0 0 0 0 0]
0 [0 0 0 0 0]


---------------
Factories:
[[3 2 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Wall:
0 [0 0 1 1 1]
1 [0 0 0 0 0]
1 [0 0 0 0 0]
1 [0 0 0 0 0]
0 [0 0 0 0 0]


---------------
Factories:
[[3 2 0 0 0]
 [0 0 0 0 0]
 [0 0 

-667

In [4]:
from stable_baselines import PPO2
from stable_baselines.common import make_vec_env
from stable_baselines.common.env_checker import check_env
from stable_baselines.common.evaluation import evaluate_policy
from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.callbacks import EvalCallback

env = AzulEnv()
check_env(env)

In [6]:
env = AzulEnv()
state = env.factories.state
obs = env.reset()
model = PPO2(MlpPolicy, env)
print(state)
print(model.predict(obs, deterministic=True)[0])

[[0 0 0 0 0]
 [0 1 1 2 0]
 [1 0 0 1 2]
 [1 1 1 0 1]
 [0 2 1 1 0]
 [2 0 2 0 0]]
[4 3 0]


In [10]:
env = AzulEnv()
evaluate_policy(model, env, deterministic=False, n_eval_episodes=100)

(-641.38, 52.03840504857926)

In [8]:
model = PPO2.load('../rl-baselines-zoo/logs/ppo2/azul-v0_13/best_model.zip')
print(state)
print(model.predict(obs, deterministic=False)[0])

Loading a model without an environment, this model cannot be trained until it has a valid environment.
[[0 0 0 0 0]
 [0 1 1 1 1]
 [1 0 1 0 2]
 [0 1 1 0 2]
 [0 0 2 1 1]
 [1 2 0 1 0]]
[2 2 0]


In [9]:
env = AzulEnv()
evaluate_policy(model, env, deterministic=False, n_eval_episodes=100)

(16.2, 75.3140093209756)

# Reward on win / loss

In [8]:
env = AzulEnv(adv_model_path='../rl-baselines-zoo/logs/ppo2/azul-v0_13/best_model.zip', reward_type='win')
model = PPO2(MlpPolicy, env)
evaluate_policy(model, env, deterministic=False, n_eval_episodes=100)

Loading a model without an environment, this model cannot be trained until it has a valid environment.


(-1.0, 0.0)

In [9]:
env.reset()
model = PPO2.load('../rl-baselines-zoo/logs/ppo2/azul-win-v0_3/best_model.zip')
evaluate_policy(model, env, deterministic=False, n_eval_episodes=100)

Loading a model without an environment, this model cannot be trained until it has a valid environment.


(-1.0, 0.0)